#!/bin/sh
cd "$(dirname "$0")" || exit   # robust oavsett om skriptet körs som ./Allmesh, bash Allmesh eller med full sökväg
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions
cleanCase0 2>/dev/null || cleanCase
rm -rf constant/triSurface/*.stl constant/extendedFeatureEdgeMesh
