#!/bin/sh
cd "$(dirname "$0")" || exit   # robust oavsett om skriptet körs som ./Allmesh, bash Allmesh eller med full sökväg
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
mkdir -p constant/triSurface && cp -f geometry/rider.stl geometry/bike.stl geometry/wheel_*.stl constant/triSurface/
runApplication surfaceFeatureExtract
runApplication blockMesh
runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite
runParallel checkMesh
