#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
mkdir -p constant/triSurface && cp -f geometry/rider.stl geometry/bike.stl geometry/wheel_*.stl constant/triSurface/
runApplication surfaceFeatureExtract
runApplication blockMesh
runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite
runParallel checkMesh
