#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
# fräscha 0-fält i varje processor (fungerar tack vare setConstraintTypes)
for d in processor*; do rm -rf "$d/0" "$d"/[1-9]*; cp -r 0 "$d/0"; done
rm -rf postProcessing log.potentialFoam log.simpleFoam
runParallel potentialFoam -writephi
runParallel $(getApplication)
